[build]
target-dir = "out/rust"
[env]
BORING_BSSL_FIPS_PATH = { value = "vendor/boringssl-fips/linux_x86_64", force = true, relative = true }
BORING_BSSL_FIPS_INCLUDE_PATH = { value = "vendor/boringssl-fips/include/", force = true, relative = true }

[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/janrueth/boring-rustls-provider"]
git = "https://github.com/janrueth/boring-rustls-provider"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
